// src/react/jsx/onEvents.tsx
import { useEffect } from "react";
import { CTX, Callback, Events } from "../../engine/types";

function onEvents<E extends Events>(this: CTX, callback: Callback<E, "response">) {
    useEffect(() => {
        this.callbackEvents.add(callback);
        () => this.callbackEvents.delete(callback)
    })
};

export default onEvents;

// src/solid/jsx/onEvents.tsx
import { onCleanup, onMount } from "solid-js";
import { CTX, Callback, Events } from "../../engine/types";

function onEvents<E extends Events>(this: CTX, callback: Callback<E, "response">) {
    onMount(() => this.callbackEvents.add(callback))
    onCleanup(() => this.callbackEvents.delete(callback))
};

export default onEvents;
