// src/solid/jsx/WebSocket.tsx
import { Component, Context, JSX } from "solid-js";

interface WebSocket extends JSX.HTMLAttributes<HTMLDivElement> {
    context: Context<any>
};

const WebSocket: Component<WebSocket> = (props) => (
    <props.context.Provider value={props.context.defaultValue}>
        {props.children}
    </props.context.Provider>
)

export default WebSocket;

// src/react/jsx/WebSocket.tsx
import React from "react";
import { Context } from "../../engine/types";

interface WebSocket extends React.HTMLAttributes<HTMLDivElement> {
    context: {
        Context: React.Context<Context>;
        defaultValue: Context;
    };
}

const WebSocket: React.FC<WebSocket> = ({ context, children }) => {
    return (
        <context.Context.Provider value={context.defaultValue}>
            {children}
        </context.Context.Provider>
    )
}

export default WebSocket;
